### ISSUE TITLE
Can you use secondary storage to test?

### ISSUE THREAD

**Issue by jscott0918** [hdinsight/tpcds-hdinsight#3]
I'm attempting to populate data to a secondary storage location that I am able to query using hdfs commands (ls, df, etc.)

Using the argument LOCATION=protocol://hostname/HDFS directory, is there any obvious reason this wouldn't work with this benchmark/data generation tool?

**Comment by dharmeshkakadia** [comment]
Yes, that should work. 
You also should modify https://github.com/hdinsight/tpcds-hdinsight/blob/master/ddl/createAllORCTables.hql#L2 with a LOCATION clause pointing to your secondary storage, since by default the internal ORC tables would be created under hive warehouse dir on primary storage.

**Comment by jscott0918** [comment]
So does this make sense?
  create table inventory
  (
      inv_item_sk          bigint,
      inv_warehouse_sk        bigint,
      inv_quantity_on_hand    int 
  )
  partitioned by (inv_date_sk bigint)
  stored as ORC
  *location '${hiveconf:LOCATION}/inventory'*;

**Comment by dharmeshkakadia** [comment]
You don't need to modify individual table definitions. 
As I mentioned in the comment above, you just need to add LOCATION=protocol://hostname/HDFS to the database creation line 2. For example,

CREATE DATABASE IF NOT EXISTS ${hiveconf:ORCDBNAME} location wasb://container@account.blob.core.windowns.net/path/to/dir'
