### ISSUE TITLE
Error after running initial datagen

### ISSUE THREAD

**Issue by jscott0918** [hdinsight/tpcds-hdinsight#4]
Receive errors following initial data generation:

OK
DBGEN2 Population Generator (Version 1.4.0)	NULL
Copyright Transaction Processing Performance Council (TPC) 2001 - 2015	NULL
log4j:ERROR Could not find value for key log4j.appender.CLA	NULL
log4j:ERROR Could not instantiate appender named "CLA".	NULL
log4j:ERROR Could not find value for key log4j.appender.CLA	NULL
log4j:ERROR Could not instantiate appender named "CLA".	NULL
log4j:ERROR Could not find value for key log4j.appender.CLA	NULL
log4j:ERROR Could not instantiate appender named "CLA".	NULL
log4j:ERROR Could not find value for key log4j.appender.CLA	NULL
log4j:ERROR Could not instantiate appender named "CLA".	NULL
log4j:ERROR Could not find value for key log4j.appender.CLA	NULL
log4j:ERROR Could not instantiate appender named "CLA".	NULL
log4j:ERROR Could not find value for key log4j.appender.CLA	NULL

**Comment by dharmeshkakadia** [comment]
That's warning for logging. You can ignore this.
