### ISSUE TITLE
Translate CTAS statements to allow LOCATION clause

### ISSUE THREAD

**Issue by jscott0918** [hdinsight/tpcds-hdinsight#5]
I don't think Hive supports using CTAS with a LOCATION clause, meaning that statements like [this](https://github.com/hdinsight/tpcds-hdinsight/blob/16cf081e9106bfba08e9901eb0c144fdef8975c1/ddl/createAllORCTables.hql#L618) can't be used to create ORC tables on secondary storage.

Is there a way to modify these to not use CTAS and allow for these ORC tables to be created on secondary storage?

**Comment by dharmeshkakadia** [comment]
Does the suggestion given in https://github.com/hdinsight/tpcds-hdinsight/issues/3#issuecomment-326703352 not work for you ?

**Comment by jscott0918** [comment]
Ah, it does make sense. I posted this before that comment was up.  Thanks!

**Comment by dharmeshkakadia** [comment]
np. Can you please all the three issues, once you verify it works for you ?

**Comment by jscott0918** [comment]
Thanks, this worked. I did have a read error on one of the ORC table creates, and the analyze step failed. I had to go run the ORC table create again for that table to get the analyze to work correctly. Still, pleased its working.  Thanks for the help!
