### ISSUE TITLE
SQL query typos

### ISSUE THREAD

**Issue by mave89** [hdinsight/tpcds-hdinsight#9]
All the queries with "interval #num days" will fail. "days" is a typo, it should be "day".

**Comment by dharmeshkakadia** [comment]
What version of Hive are you using? 
Hive 2.2 added standard SQL syntax - days, hours etc. https://issues.apache.org/jira/browse/HIVE-13557

cc @ashitgosalia

**Comment by mave89** [comment]
I see, that makes sense now. Maybe we can add this bit of information in the README. But thanks for pointing that link. Good to know.
